# Generated by Django 4.0.4 on 2023-09-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, default=18),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='profile',
            name='support_number',
            field=models.BigIntegerField(blank=True, default=9800097000),
        ),
    ]
